[PATHS]
source_dir = E:\iPhone
dest_dir   = E:\iPhone_Organized

[MODE]
; copy or move
operation = copy   

; true or false     
dry_run   = true        

[FEATURES]
enable_duplicate_check = false
duplicates_log = duplicates.log

[UI]
show_progress_bar = true

[FILES]
image_extensions = .jpg,.jpeg,.heic,.png,.webp
video_extensions = .mov,.mp4
